ALTER TABLE slots ADD COLUMN amount DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE slots ADD COLUMN currency VARCHAR(10) NOT NULL DEFAULT 'CNY';
ALTER TABLE slots ADD COLUMN duration INT NOT NULL COMMENT 'minutes';
ALTER TABLE slots ADD COLUMN type VARCHAR(20) NOT NULL DEFAULT 'online';
ALTER TABLE slots ADD COLUMN detail TEXT;